###########################################################
# environment.yml - software for project "umber"
#
# This file specifies the software packages required for this project
# in a format that the "conda" package and environment manager understands.
#
# To use it, first install anaconda or minicoda from e.g.
# http://conda.pydata.org/miniconda.html, which
# creates and installs itself in ~/anaconda/ by default,
# and alters your PATH to include ~/anaconda/bin/
#
# Next tell conda to download and install the packages listed below,
# creating a new "environment" which can be "activated".
# (Typically you only do this once.)
#
#     $ conda env create --file environment.yml
#
# Finally, to use this environment you "activate" it, which
# essentially puts ~/anaconda/envs/umber/bin/) into your PATH.
# ("source" is a shell builtin. "activate" needs to already 
# in your PATH, i.e. ~/anaconda/bin/activate).
# (Typically you do this whenever you start working on the project.)
#
#     $ source activate umber
#
# The command line prompt changes to indicate the current environment,
# and you can see the change by checking explicitly, e.g.
#
#     (umber)$ which python
#     ~/anaconda/envs/umber/bin/python
#
# In theory the command "source deactivate" will undo the "source activate".
# However this is apparently buggy and gives a "too many arguments" error,
# I think because of whitespace in my PATH. In practice I just close the 
# umber environment terminal and open a new one instead.
#
# To addd or update software packages, just invoke "conda install"
# or "conda update" after the environment has been activated.
#
# See http://conda.pydata.org/docs/commands.html for more, e.g.
#   $ conda env export       # output package specs like those in this file
#   $ conda install <package>
#   $ conda update  <package> 
#
# Tested on osx-64 (MacOS 10.11.4)
# Jim Mahoney | cs.marlboro.edu | April 2016
###############################################

# syntax notes:  version wildcards e.g. 2.6.* are allowed;
#                see https://github.com/conda/conda-env

name: umber
dependencies:
- flask=0.10.*
- git=2.6.*
- openssl=1.0.2g
- pyopenssl=0.15.1
- python=2.7.11
- pyyaml=3.11
- sqlalchemy=1.0.*
- sqlite=3.9.*
- yaml=0.1.*
- pip:
  - arrow==0.7.*              # time - do I still need this with peewee?
  - peewee=2.8.*              # possible alternative to sqlalchemy
  - python-dateutil==2.5.3    # for peewee: "import datetime"

